services:
  docs:
    image: ip_scanning_local_docs
    container_name: ip_scanning_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./ip_scanning:/app/ip_scanning:z
    ports:
      - '9000:9000'
    command: /start-docs
